### ISSUE TITLE
client crashes after clicking the Skin Customization button, apparently it's because of citadel

### ISSUE THREAD

**Issue by Wedge1453** [Alex-the-666/Citadel#34]
[crash-2021-06-10_15.16.56-client.txt](https://github.com/Alex-the-666/Citadel/files/6632065/crash-2021-06-10_15.16.56-client.txt)

**Comment by liuseniubi** [comment]
Same here.

**Comment by Gerdathlete** [comment]
Same issue occurring with the Better Minecraft Forge pack using Citadel.

**Comment by Alex-the-666** [comment]
should be fixed in 1.7.2.
