### ISSUE TITLE
Memory Leak: `EntityProperties` prevent Entitys from being garbage collected.

### ISSUE THREAD

**Issue by MaPePeR** [Alex-the-666/Citadel#38]
ResourcefulBees' apiary breeder creates temporary entitys to do it's breeding. That can create a lot of Entitys. That wouldn't be as bad in itself, if Citadel wouldn't prevent the entitys from being garbage collected. See Resourceful-Bees/ResourcefulBees#266

This is one of the hard references of an `ResourcefulBee`:
![image](https://user-images.githubusercontent.com/527679/125187046-eb0f8280-e22d-11eb-847e-4dd7bfb4b497.png)

The [`EntityDataHandler`](https://github.com/Alex-the-666/Citadel/blob/c7f00c62159f7fa0636bc6a7c880563236194d03/src/main/java/com/github/alexthe666/citadel/server/entity/EntityDataHandler.java#L16) creates a `WeakIdentityHashMap<Entity, List<IEntityData<?>>>`, but the `WeakIdentityHashMap` is only Weak-Referenced in its keys. [`EntityProperties`](https://github.com/Alex-the-666/Citadel/blob/master/src/main/java/com/github/alexthe666/citadel/server/entity/EntityProperties.java) (implementing `IEntityData`) and all subclasses keep a hard reference to the `Entity` Object preventing it from being garbage collected causing a memory leak.

**Comment by Alex-the-666** [comment]
Does the config option in citadel.cfg not work?

**Comment by MaPePeR** [comment]
Setting `"Track Entities" = false` did indeed fix the memory leak. Not sure what's the other consequences of that are, though. I guess you do Entity-Tracking for a reason? Didn't expect to find a "don't memory leak"-option, so I didn't really look, to be honest.

A real fix would probably be to also store a `WeakReference` in `EntityProperties`? Since `entity` is already private the subclasses should go through `getEntity()` anyway, which could then resolve the `WeakReference`. Subclasses would need to be aware of the possibility of getting `null` from `getEntity()`, though.

**Comment by Alex-the-666** [comment]
Got it, from 1.7.2 onwards entity will be a WeakReference.
