### ISSUE TITLE
Crash With Version 1.7.2-1.16.5

### ISSUE THREAD

**Issue by celsiusqc** [Alex-the-666/Citadel#44]
https://gist.github.com/celsiusqc/432a46fea57e207094ec01227890a4c7

**Comment by celsiusqc** [comment]
![image](https://user-images.githubusercontent.com/63996164/127266308-be063694-be4e-48b6-8610-7922734d1c5b.png)
small exchange of devs who seem to point towards citadel being the cause, hence why i posted it here

**Comment by Veynam** [comment]
Hello, I'm having the same issue with citadel and ice and fire,

Here's my crash report: https://pastebin.com/8XPJu42r

**Comment by Alex-the-666** [comment]
Downgrade citadel for now, wait for ice and fire update to fix incompatibility
