### ISSUE TITLE
1.7.3-1.16.5 server crash

### ISSUE THREAD

**Issue by kreezxil** [Alex-the-666/Citadel#45]
server crash report:
https://gist.github.com/draelock/a7b914371ec295dd8bb27b8e182b5c2a

forge: 36.2.2
mc: 1.16.5

last non-crashing citadel:
1.7.1-1.16.5

**Comment by kreezxil** [comment]
https://gitlab.com/kreezxil/world-of-dragons-2/-/issues/190

**Comment by Veynam** [comment]
Yup this mod in combination with ice and fire causes a crash for me too

**Comment by Alex-the-666** [comment]
Downgrade citadel for now, wait for ice and fire update to fix incompatibility
