### ISSUE TITLE
I don't know what to say other than 200,000 lines of error 1.16.5.

### ISSUE THREAD

**Issue by PlatiniumOfficial** [Alex-the-666/Citadel#46]
I share in a zip for TXT files the weight is completely absurd there is a crash logs "ice and fire", no idea where I should post this but well the same dev. for the 2 mods.

https://www.mediafire.com/file/a4l4y9anni9k5su/citadel_%2526_ice_and_fire.zip/file

**Comment by Alex-the-666** [comment]
Downgrade citadel for now, wait for ice and fire update to fix incompatibility
