### ISSUE TITLE
Class loading errors on Citadel 1.8.1 (Forge 36.2.4)

### ISSUE THREAD

**Issue by GitFrog1234** [Alex-the-666/Citadel#51]
### NEVERMIND, IGNORE THIS ISSUE, I WAS AN IDIOT AND DOWNLOADED THE WRONG FILE.

---------------------------------------------------------------------------------------

I'm using **Forge ver36.2.4**, installed on **Minecraft ver1.16.5**. I have no resource or data packs installed, and **the only thing in my mods folder is citadel-1.8.1-deobf.jar**.
If it makes a difference, I **edited the Forge profile in the launcher so it can use 8 GB of RAM instead of the default 2** - although I **tried with 2 afterward and got the same result**.

Whenever I try to run the game, it gives me the following message:

![image](https://user-images.githubusercontent.com/11490415/131922155-960fea5d-0337-442c-ad32-51b949cbded4.png)

The crash log is as follows:

[crash-2021-09-02_14.46.05-fml.txt](https://github.com/Alex-the-666/Citadel/files/7102011/crash-2021-09-02_14.46.05-fml.txt)
> ---- Minecraft Crash Report ----
> // You're mean.
> 
> Time: 9/2/21 2:46 PM
> Description: Mod loading error has occurred
> 
> java.lang.Exception: Mod Loading has failed
> 	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
> 	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft$$Lambda$3641/1379186202.run(Unknown Source) [?:?] {}
> 	at net.minecraft.util.Util.func_215077_a(Util.java:320) [?:?] {re:classloading}
> 	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft$$Lambda$3422/701760998.accept(Unknown Source) [?:?] {}
> 	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
> 	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.4.jar:36.2] {}
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$433/397309480.call(Unknown Source) [forge-1.16.5-36.2.4.jar:36.2] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at com.github.alexthe666.citadel.Citadel.<clinit>(Citadel.java:64) ~[?:?] {re:classloading}
> -- MOD citadel --
> Details:
> 	Mod File: citadel-1.8.1-deobf.jar
> 	Failure message: Citadel has class loading errors
> 		java.lang.NoSuchMethodError: net.minecraft.item.Item$Properties.maxStackSize(I)Lnet/minecraft/item/Item$Properties;
> 	Mod Version: 1.8.1
> 	Mod Issue URL: https://github.com/Alex-the-666/Citadel/issues
> 	Exception message: java.lang.NoSuchMethodError: net.minecraft.item.Item$Properties.maxStackSize(I)Lnet/minecraft/item/Item$Properties;
> Stacktrace:
> 	at com.github.alexthe666.citadel.Citadel.<clinit>(Citadel.java:64) ~[?:?] {re:classloading}
> 	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51] {}
> 	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:61) ~[?:36.2] {re:classloading}
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:76) ~[?:36.2] {re:classloading}
> 	at net.minecraftforge.fml.ModLoader.buildModContainerFromTOML(ModLoader.java:302) ~[?:?] {re:classloading}
> 	at net.minecraftforge.fml.ModLoader.lambda$buildMods$29(ModLoader.java:281) ~[?:?] {re:classloading}
> 	at net.minecraftforge.fml.ModLoader$$Lambda$3035/1691678663.apply(Unknown Source) ~[?:?] {}
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
> 	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1683) ~[?:1.8.0_51] {}
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
> 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_51] {}
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
> 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_51] {}
> 	at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:283) ~[?:?] {re:classloading}
> 	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:183) ~[?:?] {re:classloading}
> 	at net.minecraftforge.fml.ModLoader$$Lambda$3032/269257589.apply(Unknown Source) ~[?:?] {}
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51] {}
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
> 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_51] {}
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
> 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_51] {}
> 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:185) ~[?:?] {re:classloading}
> 	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2896/1687702287.run(Unknown Source) ~[?:?] {}
> 	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2897/690051320.run(Unknown Source) ~[?:?] {}
> 	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:437) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
> 	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.4.jar:36.2] {}
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$433/397309480.call(Unknown Source) [forge-1.16.5-36.2.4.jar:36.2] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
> 
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.16.5
> 	Minecraft Version ID: 1.16.5
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_51, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 4577898552 bytes (4365 MB) / 8287944704 bytes (7904 MB) up to 8589934592 bytes (8192 MB)
> 	CPUs: 8
> 	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> 	ModLauncher: 8.0.9+86+master.3cf110c
> 	ModLauncher launch target: fmlclient
> 	ModLauncher naming: srg
> 	ModLauncher services: 
> 		/mixin-0.8.2.jar mixin PLUGINSERVICE 
> 		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
> 		/forge-1.16.5-36.2.4.jar object_holder_definalize PLUGINSERVICE 
> 		/forge-1.16.5-36.2.4.jar runtime_enum_extender PLUGINSERVICE 
> 		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
> 		/forge-1.16.5-36.2.4.jar capability_inject_definalize PLUGINSERVICE 
> 		/forge-1.16.5-36.2.4.jar runtimedistcleaner PLUGINSERVICE 
> 		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
> 		/forge-1.16.5-36.2.4.jar fml TRANSFORMATIONSERVICE 
> 	FML: 36.2
> 	Forge: net.minecraftforge:36.2.4
> 	FML Language Providers: 
> 		javafml@36.2
> 		minecraft@1
> 	Mod List: 
> 		forge-1.16.5-36.2.4-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |NONE      |Manifest: NOSIGNATURE
> 		forge-1.16.5-36.2.4-universal.jar                 |Forge                         |forge                         |36.2.4              |NONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
> 		citadel-1.8.1-deobf.jar                           |Citadel                       |citadel                       |1.8.1               |NONE      |Manifest: NOSIGNATURE

**Comment by Tizyfox** [comment]
what have you done to solve it?

**Comment by GitFrog1234** [comment]
I downloaded and used the **citadel-1.8.1-1.16.5.jar** file instead of **citadel-1.8.1-deobf.jar**, found on the mod's Files tab on CurseForge.
