### ISSUE TITLE
When another mod fails to load, Citadel crashes with a VillageHouseManager error.

### ISSUE THREAD

**Issue by Derpford** [Alex-the-666/Citadel#66]
Here's the [crash.txt](https://github.com/Alex-the-666/Citadel/files/8585256/crash.txt).

This has happened multiple times with different mods, and it's infuriating. It seems like every time something else fails to load, Citadel clobbers the actual error by crashing here. It's making modpack debug impossible.

**Comment by Alex-the-666** [comment]
should be fixed in 1.11.3
