### ISSUE TITLE
world crash on load[1.15.2-forge-31.2.9]

### ISSUE THREAD

**Issue by SDUBZ** [Alex-the-666/Citadel#9]
Forge: 1.15.2-31.2.9
citadel: citadel-1.1.9

logs:
[latest.log](https://github.com/Alex-the-666/Citadel/files/4774175/latest.log)

**Comment by bessiq** [comment]
Having a similar issue using the new version of Citadel. Local world hangs when preparing spawn area. The common thread seems to be this error:

`[Server-Worker-18/ERROR]: Caught exception in thread Thread[Server-Worker-18,5,SERVER]
java.lang.RuntimeException: Provider com.github.alexthe666.citadel.server.CitadelServerEvents$1.getCapability() returned null; return LazyOptional.empty() instead!`

The error goes on to mention the Mutant Beasts mod in my case, and Curios in the log @SDUBZ posted. Reverting Citadel back to 1.1.7 resolved the issue for me.

**Comment by ArMoReDfUrY** [comment]
I'm also having this issue.
Forge: 1.15.2-31.2.9
citadel: citadel-1.1.9

I'm updating to Forge: 1.15.2-31.2.19 at the moment.
reverted Citadel back to 1.1.7 until this is resolved.

**Comment by IchigoGames** [comment]
same in singeplayer it just wont load at all 
citadel-1.1.10
Forge 31.2.0

**Comment by yntel** [comment]
Also having this issue.
Citadel-1.1.10
Forge 31.2.9

Reverting to 1.1.7 fixed my issue.

**Comment by SDUBZ** [comment]
still happens with citadel-1.1.10

**Comment by ClaudiusMinimus** [comment]
Happens with citadel-1.1.10 for me too

- Minecraft Version: 1.15.2
- Operating System: Linux (amd64) version 4.15.0-99-generic
- Java Version: 1.8.0_251, Oracle Corporation
- Forge: 31.2.20
- citadel-1.1.10
[crash-2020-06-16_15.14.58-server.txt](https://github.com/Alex-the-666/Citadel/files/4789208/crash-2020-06-16_15.14.58-server.txt)
[crash-2020-06-16_15.15.14-client.txt](https://github.com/Alex-the-666/Citadel/files/4789209/crash-2020-06-16_15.15.14-client.txt)

**Comment by Virtualistik** [comment]
Turns out it was specifically Citadel and had nothing to do with rats, reverting to 1.1.7 fixed it.

**Comment by Alex-the-666** [comment]
Fixed in version 1.1.11.
